// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDC_frgXfBJ80vZgLRttbYQJJSnoZZyg',
    appId: '1:178325940201:android:8d4ccf22f8e881471fcd78',
    messagingSenderId: '178325940201',
    projectId: 'github-91716',
    storageBucket: 'github-91716.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh62EwnmeXZJxB85XI9o3oV3MM2tWSzAU',
    appId: '1:178325940201:ios:e2e166771cd1e8b11fcd78',
    messagingSenderId: '178325940201',
    projectId: 'github-91716',
    storageBucket: 'github-91716.appspot.com',
    androidClientId: '178325940201-9v3tlaf6m3lkfq0hm5o69i1ehefslolt.apps.googleusercontent.com',
    iosClientId: '178325940201-aq43m8h2oj01jlqlscc3e40m8k2vh96s.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleAppGithub',
  );
}
